name: Feature request
description: Request a new feature for this project
labels: ["feature-request"]
body:
  - type: textarea
    attributes:
      label: Describe the problem
      description: Provide a clear and concise description of what the problem is and how we should solved that.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: Provide a clear and concise description of what you want to happen and why the feature should be added.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Solution Ideas? Anything that will give us more context about the feature you are proposing!
      placeholder: Add any other context (Design, Implementation, ...) or screenshots about the feature request here.
    validations:
      required: false
